#!/bin/bash

# Creates 3 machine Azure testbed

if [ $# -eq 0 ]; then
    echo "Usage: $0 basename [packages]"
    exit 1
fi

# basename is component of global resources
baseName=$1
shift

# args from environment
location=${AZURE_LOCATION:-westus}
Sku=${AZURE_SKU:-D8s_v3}
pubKey=$AZURE_SSH_KEY
ubuntuImage=${AZURE_IMAGE:-"Canonical:UbuntuServer:18.10:latest"}
user=${AZURE_USER:-$USER}

vmSize=Standard_${Sku}
rg=$user-$baseName-rg
vnet=$baseName-vnet
subFront=$baseName-front
subBack=$baseName-back
nsgName=$baseName-nsg

adminUsername=${AZURE_USER:-azure-user}
adminPassword=$(pwgen -cny 18 1)

# Storage accounts are limited to 24 characters and only alphanumeric
# need it for boot diagnostics and serial console
storageName=$(echo $rg $adminPassword | \
		  md5sum | awk '{ print "st"substr($1,20) }')

# Logging with timestamp
log() {
    echo $(date +"%T") "$@"
}

log "Validate scripts"

# validate package args
githubPath="raw.githubusercontent.com/shemminger/azure-testbed/master/scripts/"

# rest of the args are the packages
# validate that script exists and build json arg
scriptJson='{ "fileUris" : [ '
scriptCmd=
for pkg
do
    scriptName=$pkg".sh"
    if [ ! -x scripts/$scriptName ]; then
	>&2 echo "$scriptName not found or not executable"
	exit 1
    fi
    scriptUri="https://"${githubPath}${scriptName}
    wget -q -O /dev/null $scriptUri
    if [ $? -ne 0 ]; then
	>&2 echo "$scriptUri does not exist"
	exit 1
    fi

    # doing JSON in Bash is messy
    scriptJson=${scriptJson}\"$scriptUri\"
    shift
    [ $# -eq 0 ] || scriptJson=${scriptJson}','
    scriptCmd=${scriptCmd}"./"$scriptName";"
done
scriptJson=${scriptJson}'], "commandToExecute" : "'${scriptCmd}'" }'


# AZ CLI gives chatty JSON output lets put elsewhere
TEMP=$(mktemp /tmp/az-output.XXXXXXXX)
log "Creating resources (see $TEMP)"

# Abort on error
set -e

log "Setup Azure resource group $rg in $location"

# create group / network / nsg
az group create --name $rg \
   --location $location >>$TEMP

az network vnet create -g $rg \
   --name $vnet --address-prefix 172.16.0.0/16 \
   --subnet-name $subFront \
   --subnet-prefix 172.16.1.0/24 >>$TEMP

az network vnet subnet create -g $rg \
   --vnet-name $vnet --name $subBack \
   --address-prefix 172.16.2.0/24 >>$TEMP

az network nsg create --resource-group $rg \
  --name $nsgName >>$TEMP

az network nsg rule create --resource-group  $rg \
  --nsg-name $nsgName --name allow-ssh \
  --protocol tcp --direction inbound --priority 1000 --source-address-prefix '*' \
  --source-port-range '*' --destination-address-prefix '*' --destination-port-range 22 \
  --access allow >>$TEMP

az storage account create --resource-group $rg \
   --name $storageName \
   --location $location \
   --sku Standard_LRS --kind StorageV2 >>$TEMP

## bastion server
vmPrefix=bastion1
vmSizeBastion=Standard_B1s
baseNameBastion=$vmPrefix
imageName=$ubuntuImage
publicIp=pip-$baseName
vNic=nic-$baseNameBastion

log "Creating public IP $publicIp"

az network public-ip create --resource-group $rg \
    --name $publicIp --allocation-method static --idle-timeout 4 >> $TEMP

az network nic create \
    -n $vNic \
    -g $rg \
    --subnet $subFront \
    --network-security-group $nsgName \
    --public-ip-address $publicIp \
    --vnet-name $vnet  >> $TEMP

log "Creating Bastion Server: $baseNameBastion"
az vm create \
    -g $rg \
    --os-disk-name osdisk-$baseNameBastion \
    --name vm-$baseNameBastion \
    --nics $vNic \
    --storage-sku premium_lrs \
    --size $vmSizeBastion \
    --image $imageName \
    --admin-username $adminUsername \
    --authentication-type ssh \
    --ssh-key-value "@$pubKey" \
    --no-wait >> $TEMP


# Ubuntu ACC
vmPrefix=ubuntu-acc
accNet=true
imageName=$ubuntuImage

for i in {1..2};
do
    baseNameLoop=$vmPrefix$i
    nic1=nic1-${baseNameLoop}
    nic2=nic2-${baseNameLoop}

    log "Creating $nic1 and $nic2"
    az network nic create -g $rg \
       --name $nic1 \
       --vnet $vnet \
       --subnet $subFront \
       --network-security-group $nsgName >>$TEMP

    az network nic create -g $rg \
       --name $nic2 \
       --vnet $vnet \
       --subnet $subBack \
       --network-security-group $nsgName \
       --accelerated-networking true >>$TEMP

    log "Creating vm-$baseNameLoop"
    az vm create \
        -g $rg \
        --os-disk-name osdisk-$baseNameLoop \
        --name vm-$baseNameLoop \
        --nics $nic1 $nic2 \
	--no-wait \
        --storage-sku premium_lrs \
        --size $vmSize \
        --image $imageName \
	--authentication-type all \
        --admin-username $adminUsername \
        --admin-password "$adminPassword" \
	--no-wait >>$TEMP

    log "vm-$baseNameLoop in progress"
done

# Wait for deployment
log "Waiting for VM deployment"
az vm wait --created --ids $(az vm list -g $rg --query "[].id" -o tsv) >>$TEMP

# Enable boot diagnostics
log "Enabling boot diagnostics"
az vm boot-diagnostics enable --storage $storageName \
   --ids $(az vm list -g $rg --query "[].id" -o tsv) >>$TEMP

for i in {1..2};
do
    log "Setup vm-$vmPrefix$i"
    az vm extension set \
       -g $rg --vm-name vm-$vmPrefix$i \
       --name customScript \
       --publisher Microsoft.Azure.Extensions \
       --settings "$scriptJson"
done

# Display result
echo -n 'public ip: '
az network public-ip list -g $rg \
	       --query "[].{ip:ipAddress, vm:name}" | \
	python -c 'import sys,json;print(json.load(sys.stdin)[0]["ip"])'

echo "user: $adminUsername passwd: $adminPassword"
