#!/bin/bash
# Delete resource groups f

if [ $# -lt 1 ]; then
    echo "Usage: $0 basename(s)"
    exit 1
fi

user=${AZURE_USER:-$USER}

for base
do
	rg=$user-$base-rg
	echo "Deleting Azure resource group $rg"
	az group delete --name $rg --no-wait
done
